# Generated by Django 4.1 on 2022-08-20 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('ques_description', models.TextField(max_length=1000)),
                ('level', models.CharField(choices=[('BASIC', 'BASIC'), ('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD'), ('EXPERT', 'EXPERT')], max_length=100)),
                ('gfg', models.CharField(blank=True, max_length=500, null=True)),
                ('leetcode', models.CharField(blank=True, max_length=500, null=True)),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('cplusplus_video', models.CharField(blank=True, max_length=500, null=True)),
                ('java_video', models.CharField(blank=True, max_length=500, null=True)),
                ('python_video', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
