# Generated by Django 4.1 on 2022-08-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0003_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='estimated_time',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheet', to='dsa_app.userprofile', verbose_name='user'),
        ),
    ]
