# Generated by Django 4.1 on 2022-08-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0004_remove_sheet_estimated_time_alter_sheet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('question_link', models.CharField(max_length=1000)),
                ('solution_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_app.sheet')),
            ],
        ),
    ]
