# Generated by Django 4.1 on 2022-08-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0005_userquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestion',
            name='sheet',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_app.userprofile'),
            preserve_default=False,
        ),
    ]
