# Generated by Django 4.1 on 2022-08-21 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0006_remove_userquestion_sheet_userquestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
