# Generated by Django 4.1 on 2022-08-23 18:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0007_userquestion_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
