# Generated by Django 4.1 on 2022-08-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0009_remove_userquestion_user_userquestion_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_solved',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='is_completed',
        ),
    ]
