# Generated by Django 4.1 on 2022-08-24 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0011_question_similar1_question_similar2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 24, 12, 54, 35, 691264, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
