# Generated by Django 4.1 on 2022-08-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0014_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Tags',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsa_app.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquestion',
            name='Tag',
            field=models.CharField(choices=[('Array', 'Array'), ('String', 'String'), ('LinkedList', 'LinkedList'), ('Stack', 'Stack'), ('Queue', 'Queue'), ('Tree', 'Tree'), ('BST', 'BST'), ('Graph', 'Graph'), ('Heap', 'Heap'), ('Sorting', 'Sorting'), ('Searching', 'Searching'), ('Greedy', 'Greedy'), ('DP', 'Dynamic Programming'), ('Backtracking', 'Backtracking')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_app.question'),
        ),
    ]
