# Generated by Django 4.1 on 2022-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0016_solution_solution_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='description',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
