# Generated by Django 4.1 on 2022-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0017_remove_solution_solution_solution_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enrolled',
            field=models.ManyToManyField(to='dsa_app.sheet'),
        ),
    ]
