# Generated by Django 4.1 on 2022-08-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0018_question_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='enrolled',
        ),
    ]
