# Generated by Django 4.1 on 2022-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0019_remove_question_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='enrolled',
            field=models.ManyToManyField(related_name='enrolled', to='dsa_app.userprofile'),
        ),
    ]
