# Generated by Django 4.1 on 2022-08-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0020_sheet_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_solved',
            field=models.ManyToManyField(to='dsa_app.userprofile'),
        ),
    ]
