# Generated by Django 4.1 on 2022-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_app', '0022_alter_sheet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
